### ISSUE TITLE
经安利一试后，蛮香，提些建议

### ISSUE THREAD

**Issue by GouZi2019** [Greathings-Lab/Thorn-Writing#10]
下载的0.0.9版本的，用起来体验不错，提一些建议

- 软件对高分辨率屏支持不好，2K屏开启软件有些模糊。（不想调到100%放大率，那样字太小了。很多软件都已支持150%了）
- 粘贴进来文本后编辑框会抖一下，显示文本的视图和粘之前会有变化，影响输入体验
- 希望添加源码修改功能（像typora一样ctrl+/），更可控
- 加个chrome剪藏插件吧，微信也来一个发文章自动存到笔记本。

界面简约好看，赞

**Comment by Auxxxxlx** [comment]
谢谢小伙伴的反馈。我推荐小伙伴通过 快捷键 调整应用本身的缩放比例。Ctrl+Shift+`+` 放大、Ctrl+`-` 缩小 。通过这两个快捷键，小伙伴可以找到适合自己习惯的缩放比例。
