### ISSUE TITLE
软件布局乱套了

### ISSUE THREAD

**Issue by GouZi2019** [Greathings-Lab/Thorn-Writing#11]
用的win10
更换了一个存储区域，用来做同步
但是发现切换了再退出后，再打开布局就会乱掉
按照 #9 里面的解决方案改了之后，虽然布局恢复正常，但是更换的存储区域就找不到了。
如果再把更换的存储区添加回来，再退出仍然会出现布局乱套的情况。

**Comment by Auxxxxlx** [comment]
@GouZi2019  抱歉没能即时回复小伙伴的问题，这几天在忙其他的。这个问题已经修复了哦。如果还有问题，请即时联系我们。

**Comment by Auxxxxlx** [comment]
推荐扫码加入内测微信群哦。二维码在[官网](https://thorn.greathin.gs)。
