### ISSUE TITLE
能否打开默认文件夹

### ISSUE THREAD

**Issue by cunyu1943** [Greathings-Lab/Thorn-Writing#12]
如题，能否在打开软件时，默认打开某文件夹

**Comment by Auxxxxlx** [comment]
谢谢小伙伴的反馈，目前应用已经支持记忆上次打开的文件，以及打开的笔记本，甚至每一篇文章的最后编辑位置。小伙伴每一次打开应用，都可以从上一次的文件继续编辑。

**Comment by Auxxxxlx** [comment]
@cunyu1943 抱歉没能即时回复小伙伴的问题，这几天在忙其他的，搞忘看 GitHub 了，推荐扫码加入内测微信群哦。
