### ISSUE TITLE
一个新手的使用感想

### ISSUE THREAD

**Issue by Airrs** [Greathings-Lab/Thorn-Writing#14]
小白用户，就不扯什么技术方面的问题了:D
软件还探索的比较粗略
本人学生，文字输出主要是打作业，windows用户， v0.0.11版本

先说我比较喜欢的  
1.左下这个自动保存，非常喜欢，一直在找能自动能够自动保存的文字输入软件
2.自带的纸张颜色（皮肤）设计的不错，基础使用足够了
3.导出界面格式可选和打印预览感觉很好

然后一些对未来功能的期待（其实单纯从使用来说：大功能还挺完善的
1.打字机功能
2.选择文字弹出的文字工具栏考虑过双行显示吗？初次使用觉得有点费劲，一次性展示不完，还要点击翻页……
3.预先插入空白表格功能
4.完善右键拓展功能界面

以上的文字都是在刺写里完成的，期待后续软件的开发！

**Comment by Auxxxxlx** [comment]
@Airrrs 非常感谢小伙伴的细心评价🍺🍺🍺。

### 打字机功能
这个我会列入开发计划，将会在2个版本内带来这个功能

### 浮动工具栏交互逻辑
不展示完的原因是，按钮非常多，而且现在实现的功能还不到一半，如果全部放在一级菜单展示的话，这个浮动工具栏会超级长，超级长。我们有两个方法来改善这一点。
* 通过按钮分组进行收纳 （已经实现）
* 用户可以自定义一级菜单的显示内容（已规划）：用户可以把特定的一些功能按钮放置在一级菜单，而不用展开子菜单
* 按钮组条件展示，一些特定的按钮只会在特定的节点选中才会出现，比如表格相关的操作按钮，只有选中了表格，才会出现表格的操作按钮组

### 预先插入空白表格 & 完善右键拓展功能界面
这个我们没太懂，需要小伙伴进一步描述。
