### ISSUE TITLE
反馈：「点击新建文章」按钮太不醒目了

### ISSUE THREAD

**Issue by waynecz** [Greathings-Lab/Thorn-Writing#15]
如图所示

![image](https://user-images.githubusercontent.com/11238540/67252428-a3c3ea00-f4be-11e9-8935-e6b6170e928c.png)

- MacOS 10.14.6
- 深色主题下

**Comment by Auxxxxlx** [comment]
@waynecz 谢谢小伙伴的反馈🙏，这个问题我们将会在下一个版本进行调整。

* 没有文章时，`新建文章` 的位置和样式
* 有文章时，通过右击下方文章视图也可以创建文章

**Comment by Alecyrus** [comment]
<img width="938" alt="截屏2019-10-2312 20 25" src="https://user-images.githubusercontent.com/13865581/67357336-93c80b00-f58f-11e9-85c2-9a5e6b5dd9e9.png">

**Comment by Auxxxxlx** [comment]
<img width="992" alt="截屏2019-10-2313 49 27" src="https://user-images.githubusercontent.com/55738135/67361678-f1625480-f59b-11e9-855f-a1793e523db9.png">
