### ISSUE TITLE
拖动代码块后的代码高亮问题

### ISSUE THREAD

**Issue by woxj** [Greathings-Lab/Thorn-Writing#16]
拖动代码块后需要再次回车修改才能执行高亮，如果第一次高亮回车，在移动到另一个位置后需要再执行一次Backspace操作，增加了操作步骤
![thornw2](https://user-images.githubusercontent.com/53204626/67618733-ecb0d100-f825-11e9-9b59-1b48a1d2b1d2.gif)

**Comment by Auxxxxlx** [comment]
@woxj  🖖谢谢小伙伴的反馈，这个问题将会在下个版本修复。
