### ISSUE TITLE
关于编辑器样式操作逻辑的想法

### ISSUE THREAD

**Issue by woxj** [Greathings-Lab/Thorn-Writing#17]
执行操作：打开文章>选择一行文字>点击编辑器样式>点击设置
此时`编辑器样式`设置框会浮在设置框上面，对此我存在一个疑惑，`设置`的优先级是否应该更高？让`编辑器样式设置框`显示在底部，或者关闭，或许开发者有另外的想法？(一点小疑惑)
![image](https://user-images.githubusercontent.com/53204626/67652465-08c88580-f980-11e9-8595-1942564736bc.png)

**Comment by woxj** [comment]
根据`Ctrl`+`Shift`+`+`放大时，标题栏文字会换行，（讨论）是否应该让显示不出来的字就隐藏了？而不是显示在文章区
![image](https://user-images.githubusercontent.com/53204626/67652760-57c2ea80-f981-11e9-8e44-04ef8306ae6a.png)

**Comment by woxj** [comment]
字体发虚问题，像是蒙了一层雾或者高斯模糊
![image](https://user-images.githubusercontent.com/53204626/67653243-9063c380-f983-11e9-967d-f3ef601d3bf7.png)

**Comment by Auxxxxlx** [comment]
谢谢小伙伴的细心评测！🍺🍺🍺。
前两个问题将会在下个版本修复。对于字体发虚的问题，的确对字体添加了阴影，以模拟柔和字体边缘，模拟电子墨水屏的渲染效果。字体渲染高度的锐利，这的确会增加可辨认性，但是合适的字体边缘模糊，会让视觉效果更加柔和。这是我们目前在字体渲染上的选择。后期会支持会渲染效果进行调整，但的确目前是会让习惯了 Windows 字体渲染方式的用户感觉不习惯。

**Comment by woxj** [comment]
@Auxxxxlx 理解开发者的选择
