### ISSUE TITLE
# FeatureRequest for Mac version

### ISSUE THREAD

**Issue by AltheaL55** [Greathings-Lab/Thorn-Writing#18]
1. 希望可以改善页面切换流畅度，比如左侧边栏的展开和收起、设置界面的展开和切换，过于缓慢且略有卡顿；
2. 希望可以选择不显示编辑器文字周围的光晕/掩膜？看起来不清晰；
3. 字体切换模式复杂，非设计领域用户可能平常并不关注“字体值”，或甚至并不能拼出字体全称。请考虑使用传统下拉栏形式；
4. 在左边栏展开的情况下，选中文字调整格式并展开选项框，会出现被左边栏遮挡的情况，见下图
![image](https://user-images.githubusercontent.com/44015504/67730123-f8bbaf00-fa2e-11e9-8a0d-33ba9dfebed1.png)
5. 鼠标初次移至文本格式选项框的图标上时，操作提示文本（如“引用”、“代码块”等）出现较慢，有明显等待时间，但此后平移至其他图标则提示文本出现较快，建议优化
5. 插入表格的按钮习惯性直接点击，则展开行/列操作和合并/拆分选项，而整体选项框左移，鼠标已偏离原始添加表格位置，初次使用未能理解需下移至下方加号处才完成添加，建议考虑调整操作设计。
6. 表格输入时，仍有与文字等高的灰色highlight背景，但与表格单元格边框相距甚远，略不协调。
7. 希望考虑在顶部菜单栏的Thorn下添加“偏好设置（preferences）”更改设置，更符合用户习惯，并添加更多可设置选项，如添加用户支持多端同步、支持夜间模式、默认表格行列数、字数统计显示等。
感谢开发者。建议如上，望考虑。

**Comment by Auxxxxlx** [comment]
@AltheaL55 感谢小伙伴的细心评测

> 希望可以改善页面切换流畅度，比如左侧边栏的展开和收起、设置界面的展开和切换，过于缓慢且略有卡顿

答：在我们的测试环境（macbook pro 13 2019 、 matebook 14 i5+8GB ），小伙伴说的这些操作，都没有出现卡顿，基本都非常流畅，请进一步提供你的电脑配置以及相关运行环境说明。

> 希望可以选择不显示编辑器文字周围的光晕/掩膜？看起来不清晰；

答：请等待后期的更新，将支持用户对渲染效果进行自定义设置。

> 字体切换模式复杂，非设计领域用户可能平常并不关注“字体值”，或甚至并不能拼出字体全称。请考虑使用传统下拉栏形式；

答：请参考官网博客[相关文章](https://thorn.greathin.gs/blog/files/a4be7fc21f48fca64ea92ef5fe435e3a-0.html)，我们给出了非常详细的操作说明。后期将优化管理字体的体验。请继续关注。

> 在左边栏展开的情况下，选中文字调整格式并展开选项框，会出现被左边栏遮挡的情况。

答：这个问题暂时无法修复，macOS 用户点击工具栏任一图标，将自动重设位置，Windows 用户目前没有方案解决这个问题，请期待后续更新。

> 鼠标初次移至文本格式选项框的图标上时，操作提示文本（如“引用”、“代码块”等）出现较慢，有明显等待时间，但此后平移至其他图标则提示文本出现较快，建议优化。

答：这个问题非常希望小伙伴可以进行进一步描述，提供录屏 gif， 我们暂时没能理解。

> 插入表格的按钮习惯性直接点击，则展开行/列操作和合并/拆分选项，而整体选项框左移，鼠标已偏离原始添加表格位置，初次使用未能理解需下移至下方加号处才完成添加，建议考虑调整操作设计。

答：只需要 把鼠标移动至表格图标处，就会出现相关的添加菜单，点击 + 号，就可以插入表格。点击表格图标，则出现表格相关的操作按钮。这里暂时不会做调整。

> 表格输入时，仍有与文字等高的灰色highlight背景，但与表格单元格边框相距甚远，略不协调。

答：灰色高亮标识了当前的焦点层级。高亮只和内部元素有关，和外部元素无关。

> 希望考虑在顶部菜单栏的Thorn下添加“偏好设置（preferences）”更改设置，更符合用户习惯，并添加更多可设置选项，如添加用户支持多端同步、支持夜间模式、默认表格行列数、字数统计显示等。
感谢开发者。建议如上，望考虑。

答：下个版本将会添加“顶部菜单栏”的相关选项；多端同步请期待后期更新；默认表格行列数请期待下个版本；字数统计就在右下角哦！！我们不会支持夜间模式，我们只会推出相关的暗色纸张。

谢谢小伙伴这么细心！！！🍺🍺🍺
