### ISSUE TITLE
#day issue latex 行内公式渲染问题以及行间公式操作问题

### ISSUE THREAD

**Issue by woxj** [Greathings-Lab/Thorn-Writing#19]
1. 行内公式渲染文字重叠
![image](https://user-images.githubusercontent.com/53204626/67756422-f7ad7080-fa74-11e9-9a6c-82148a4ac1ff.png)
2. 输入完行间公式回车不能下一行
![thornw3](https://user-images.githubusercontent.com/53204626/67756530-21669780-fa75-11e9-83bf-9db6d4703e15.gif)

**Comment by Auxxxxlx** [comment]
谢谢小伙伴的回复，请查看 #20
