### ISSUE TITLE
Latex 块编辑完后渲染[Feature request]

### ISSUE THREAD

**Issue by Steven-AA** [Greathings-Lab/Thorn-Writing#20]
Latex 实时渲染在编辑一些稍微复杂公式的时候并不方便，倒不如退出公式块之后再渲染，进入公式块之后仍然显示文本来进行编辑，而且文本最好能支持并保存换行，对复杂公式的编辑会比较友好。

当然，实时渲染可能对少量简单公式编辑会非常直观，至少给用户一个开关自己选择会好一点。

此外，最好用方向键就能进出公式块，现在的公式块必须点击，很不方便。https://github.com/Greathings-Lab/Thorn-Writing/issues/19 也提到了这一点。

**Comment by Auxxxxlx** [comment]
谢谢小伙伴的回复，Latex 公式小伙伴可以使用快捷键直接编辑 Latex 源码，在源码编辑框中使用 Tab 进行即时渲染。实时渲染支持快捷键和语法联想（使用 \ 触发）。 退出和进入公式，我们早已做了优化，通过方向键和Enter可退出公式编辑。请期待下个大版本更新。

**Comment by Auxxxxlx** [comment]
小伙伴的 “编辑完后渲染” 我们将不会支持，请使用公式源码编辑框或者公式语法联想代替。

**Comment by Steven-AA** [comment]
就是那个`Latex的源码编辑操作栏`能大一点吗
![image](https://user-images.githubusercontent.com/22387129/68177334-f45d3c00-ffc2-11e9-86da-5d33ee4e9336.png)

**Comment by Auxxxxlx** [comment]
您好！

目前内部 Aplha 产品原型测试已经借宿，目前的版本将会停留在v0.1.0-beta（产品原型版本）, 下个版本（v0.2.0) 将会带来全新设计的 荆棘写作，敬请期待！！

关于 “ Latex的源码编辑操作栏 ” 的问题： 已收到， 将会在 v0.2.0 重新设计公式编辑的交互设计！



荆棘写作 x Rose （v.0.2.0）开发前瞻：
