### ISSUE TITLE
Qt 写的？

### ISSUE THREAD

**Issue by petcat** [Greathings-Lab/Thorn-Writing#21]
不是开源的
然后就把github当成说明和讨论真的好？

**Comment by Auxxxxlx** [comment]
我们现在主要是使用Github 作为应用分发渠道之一，然后利用 Issue 进行问题收集和追踪，这并没有什么不妥啊？ 不太明白这有什么好不好的问题。

我们没有精力再去维护一个讨论组或者社区论坛，使用 Issue 是目前我们采用的方案，如果触犯了相关协议和条款，请小伙伴进一步说明。
