### ISSUE TITLE
官网内测群二维码失效

### ISSUE THREAD

**Issue by liangpeili** [Greathings-Lab/Thorn-Writing#22]
如题，希望更换新的二维码。谢谢~

**Comment by Auxxxxlx** [comment]
@liangpeili  谢谢小伙伴的关注，目前官网正在重新开放，不久将会上线新的官网。另外 荆棘写作 在进行一次全面的重构，在新官网上线后，可以进一步了解相关信息。

**Comment by Auxxxxlx** [comment]
https://thorn.greathin.gs/contact/
