### ISSUE TITLE
存储路径修改支持

### ISSUE THREAD

**Issue by mrdear** [Greathings-Lab/Thorn-Writing#5]
本地写文章多设备同步都是依靠icloud, 希望尽快增加更改存储目录功能.

**Comment by Auxxxxlx** [comment]
小伙伴你好，感谢你的反馈🙏。 云同步功能已经在计划列表，因为不只是面对 mac 用户，因此我们将支持两种云同步方案
* 官方云同步（优先级：低）
* 第三方云同步（优先级：高）

我这里做一个功能备忘，有任何建议，都可以在下方评论。
## 功能特性备忘
### 功能简述
支持存储路径修改

### 功能详述
* 新增工作空间管理功能
> 每个工作空间和特定的目录进行绑定
