### ISSUE TITLE
文章存储形式建议

### ISSUE THREAD

**Issue by mrdear** [Greathings-Lab/Thorn-Writing#6]
使用自定义文章存储功能后，发现文章都是存放在默认生成的text json里面的，这样做的话，有几个问题。
1. 类似hexo这种基于文件形式管理blog的工具无法使用，无法deploy。
2. 所有设备强制使用 荆棘写作 才能够查看到具体文章，其他文本编辑器只能看到一堆json描述符。
3. markdown都被转换为json描述了，假设我想复制markdown格式的文章到其他地方无法操作。

我的建议：

既然提供了自定义目录能力，可以考虑基于文件目录形式管理，保证文档的原汁原味，否则这个自定义云同步意义不大，软件本身可以专门搞个目录存放自己需要的数据。

![image](https://user-images.githubusercontent.com/13889883/66369047-4cf1e700-e9cd-11e9-9064-4ec01aa0b7c6.png)

**Comment by Auxxxxlx** [comment]
非常谢谢小伙伴的反馈🐄🍺。其实完全不用担心，与`小伙伴提到的问题`相关的功能，已经在开发计划里了。我这里对以下几点进行说明一下：
 *  目前存储目录都是存储的`荆棘写作`的数据文件以及相关配置，并不是`Markdown`， 这是因为`荆棘写作`其实不是一个`Markdown编辑器`，`Markdown`只是我们的兼容格式。
 * 文章发布到诸如  `Hexo` 、`Wordpress`、`Medium`等平台，以后将会通过插件的形式进行支持，到时候只要在我们的插件商店进行启用就可以啦，这是我们的 `顶屏计划` 所带来的插件功能，当然插件的功能远远不限于此。
* `荆棘写作` 将会推出自己的文章内容发布平台`荆棘 · 优刊`。
* 就目前来说，小伙伴可以通过右上角的图标呼出导出窗口，然后导出 `Markdown` 格式文件。

总的来说，`荆棘写作` 目前功能还不太完善，但是慢慢地，小伙伴会看到一个又一个强大功能特色，请继续关注并支持我们。
