### ISSUE TITLE
windows上不支持链接，图片渲染吗

### ISSUE THREAD

**Issue by youngxhui** [Greathings-Lab/Thorn-Writing#8]
windows 0.0.8 beta
![image](https://user-images.githubusercontent.com/16971804/66715558-5cbb6200-edf7-11e9-9895-76f5c85ba27d.png)

![image](https://user-images.githubusercontent.com/16971804/66715582-8f655a80-edf7-11e9-8748-87da63426800.png)

**Comment by Auxxxxlx** [comment]
感谢小伙伴的反馈🙏 （最新版 v0.0.9-beta 已发布，快去 [新版官网](https://thorn.greathin.gs/) 看看哦。）

---

## 对于图片的支持
小伙伴直接将网络图片或者本地图片`直接拖拽`进编辑区相应位置即可， 不需要输入繁复的 Markdown 语法。我们将不会对 Markdown 图片插入语法做支持 (因为太低效了),  小伙伴有三种方式插入图片，
 1. 通过浮动工具栏的插入 Unsplash 图片窗口
 2. 手动拖拽本地图片到编辑区
 3. 手动拖拽网络图片到编辑区

### 图片功能预览
* 支持图片编辑（裁剪，缩放，滤镜，旋转，图案文字标注)
* 支持图床管理
* 支持更多在线图片搜索（目前仅支持 Unsplash 图片）

## 对于链接的支持
小伙伴直接粘贴链接即可，链接将会被识别为超链接。链接的支持还不完善，马上将会带来更好的支持。
### 链接功能预览 (将在下个版本提供)
* 链接可访问性检查
* 支持自动根据链接网页的 Title 生成 超链接文本
* 支持对链接的文本内容和 URL 地址进行修改

**Comment by youngxhui** [comment]
加油啊！很看好你们。

**Comment by Alecyrus** [comment]
谢谢小伙伴的支持。🥰！
