### ISSUE TITLE
win10修改存储区域后重启，软件布局混乱

### ISSUE THREAD

**Issue by NB1231** [Greathings-Lab/Thorn-Writing#9]
window10专业版 1903,小版本18362.418
屏幕录像[recordit.co/HdOrKFu7rh](recordit.co/HdOrKFu7rh)

**Comment by NB1231** [comment]
抱歉不会做标记

**Comment by youngxhui** [comment]
![image](https://user-images.githubusercontent.com/16971804/66750895-46c5a400-eec0-11e9-8ab6-8f6964dcd3e7.png)

删除该文件，听说下一个版本会解决该问题。

**Comment by Auxxxxlx** [comment]
谢谢小伙伴们的关注。这个问题已在 v0.0.10-beta 中修复。

荆棘写作 v0.0.11-beta 已经开放下载，请在[官网](https://thorn.greathin.gs)了解更新详情并下载哦,想获得更多的新功能开发消息和更直接的反馈，请在这里扫码加入[内测微信群](https://thorn.greathin.gs/community/)。
